import { Prisma, PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import pg from "pg";
import bcrypt from "bcryptjs";
import "dotenv/config";
import {
  NotificationChannel,
  NotificationStage,
  NotificationStatus,
  Role,
  TrainingStatus,
  WorkDecisionKind,
  WorkDecisionStatus,
} from "@prisma/client";
import { registerDocumentUpload } from "../lib/document-registry";
import { buildDocumentDownloadUrl } from "../lib/document-registry-urls";

type SeededDocument = {
  documentId: number;
  documentVersionId: number;
  fileUrl: string;
  fileName: string;
};

function requireEnv(name: string) {
  const value = process.env[name]?.trim();
  if (!value) {
    throw new Error(`Missing required env var: ${name}`);
  }
  return value;
}

function makeSeedTag(namespace: string, key: string) {
  return `seed:${namespace}:${key}`;
}

function uniqueStrings(values: string[]) {
  return Array.from(new Set(values.filter(Boolean)));
}

function daysFromNow(days: number, hourLocal = 9, minuteLocal = 0) {
  const now = new Date();
  const value = new Date(now);
  value.setDate(value.getDate() + days);
  value.setHours(hourLocal, minuteLocal, 0, 0);
  return value;
}

function toKenyanPhone(msisdn: string) {
  const trimmed = msisdn.trim();
  if (trimmed.startsWith("+254")) return trimmed;
  if (trimmed.startsWith("254")) return `+${trimmed}`;
  if (trimmed.startsWith("0")) return `+254${trimmed.slice(1)}`;
  return trimmed;
}

function buildReceiptText(input: {
  authority: "KRA" | "NSSF" | "SHA";
  receiptNo: string;
  date: string;
  amountKes: number;
  payer: string;
  pin?: string;
  prn?: string;
}) {
  // Keep this plain text: it seeds the OCR/extraction pipeline even without PDFs.
  const lines: string[] = [];
  lines.push(`${input.authority} PAYMENT RECEIPT`);
  lines.push(`Receipt Number: ${input.receiptNo}`);
  if (input.prn) lines.push(`PRN: ${input.prn}`);
  lines.push(`Filing/Payment Date: ${input.date}`);
  lines.push(`Payer: ${input.payer}`);
  if (input.pin) lines.push(`PIN: ${input.pin}`);
  lines.push(`Amount: KES ${input.amountKes.toLocaleString("en-KE", { maximumFractionDigits: 2 })}`);
  lines.push(`Status: SUCCESS`);
  lines.push(`Generated by BHL demo seed`);
  return `${lines.join("\n")}\n`;
}

const pool = new pg.Pool({
  connectionString: requireEnv("DATABASE_URL"),
  ssl: process.env.DATABASE_SSL === "disable" ? undefined : { rejectUnauthorized: false },
});
type PrismaPgArgs = ConstructorParameters<typeof PrismaPg>[0];
const adapter = new PrismaPg(pool as unknown as PrismaPgArgs);
const prisma = new PrismaClient({ adapter });

async function upsertOrganization(input: { slug: string; name: string }) {
  return prisma.organization.upsert({
    where: { slug: input.slug },
    update: { name: input.name },
    create: { slug: input.slug, name: input.name },
  });
}

async function upsertUser(input: {
  organizationId: number;
  email: string;
  name: string;
  role: Role;
  phoneNumber?: string;
  whatsappOptIn?: boolean;
  passwordPlain?: string;
}) {
  const hashedPassword = bcrypt.hashSync(input.passwordPlain || "password123", 10);
  const phoneNumber = input.phoneNumber ? toKenyanPhone(input.phoneNumber) : null;

  return prisma.user.upsert({
    where: { email: input.email },
    update: {
      name: input.name,
      role: input.role,
      phoneNumber,
      whatsappOptIn: input.whatsappOptIn ?? false,
      whatsappConsentAt: input.whatsappOptIn ? new Date() : null,
      organizationId: input.organizationId,
      password: hashedPassword,
      isActive: true,
    },
    create: {
      email: input.email,
      name: input.name,
      role: input.role,
      phoneNumber,
      whatsappOptIn: input.whatsappOptIn ?? false,
      whatsappConsentAt: input.whatsappOptIn ? new Date() : null,
      organizationId: input.organizationId,
      password: hashedPassword,
      isActive: true,
    },
  });
}

async function upsertClientEntity(input: {
  organizationId: number;
  name: string;
  code?: string | null;
}) {
  return prisma.clientEntity.upsert({
    where: {
      organizationId_name: {
        organizationId: input.organizationId,
        name: input.name,
      },
    },
    update: { code: input.code ?? null, isActive: true },
    create: {
      organizationId: input.organizationId,
      name: input.name,
      code: input.code ?? null,
      isActive: true,
    },
  });
}

async function ensureWorkItem(input: {
  namespace: string;
  key: string;
  organizationId: number;
  clientEntityId?: number | null;
  userId: number;
  title: string;
  category: string;
  deadline: Date;
  frequency: string;
  responsible: string;
  requiredDocumentLabel: string;
  status?: string;
  riskScore?: string | null;
}) {
  const seedTag = makeSeedTag(input.namespace, input.key);
  const namespaceTag = makeSeedTag(input.namespace, "namespace");

  const existing = await prisma.workItem.findFirst({
    where: {
      organizationId: input.organizationId,
      archivedAt: null,
      aiTags: { has: seedTag },
    },
    select: { id: true, aiTags: true },
  });

  const aiTags = uniqueStrings([namespaceTag, seedTag, ...(existing?.aiTags || [])]);

  if (existing) {
    return prisma.workItem.update({
      where: { id: existing.id },
      data: {
        title: input.title,
        category: input.category,
        deadline: input.deadline,
        frequency: input.frequency,
        responsible: input.responsible,
        requiredDocumentLabel: input.requiredDocumentLabel,
        status: input.status ?? "Pending",
        riskScore: input.riskScore ?? null,
        remindDaysBefore: 3,
        organizationId: input.organizationId,
        clientEntityId: input.clientEntityId ?? null,
        userId: input.userId,
        aiTags: { set: aiTags },
        aiPriorityIndex: 0.7,
      },
    });
  }

  return prisma.workItem.create({
    data: {
      title: input.title,
      category: input.category,
      deadline: input.deadline,
      frequency: input.frequency,
      responsible: input.responsible,
      requiredDocumentLabel: input.requiredDocumentLabel,
      status: input.status ?? "Pending",
      riskScore: input.riskScore ?? null,
      remindDaysBefore: 3,
      organizationId: input.organizationId,
      clientEntityId: input.clientEntityId ?? null,
      userId: input.userId,
      aiTags,
      aiPriorityIndex: 0.7,
    },
  });
}

async function replaceChecklist(workItemId: number, labels: string[]) {
  await prisma.workItemChecklistItem.deleteMany({ where: { workItemId } });
  await prisma.workItemChecklistItem.createMany({
    data: labels.map((label, idx) => ({
      workItemId,
      label,
      sortOrder: idx + 1,
      isDone: false,
    })),
  });
}

async function upsertApproval(input: {
  workItemId: number;
  submittedById: number;
  decidedById: number;
  status: "Submitted" | "Approved" | "Rejected";
  submissionNote?: string;
  managerResponseKind?: string;
  managerResponseLabel?: string;
  managerResponseNote?: string;
}) {
  const existing = await prisma.workItemApproval.findFirst({
    where: { workItemId: input.workItemId },
    orderBy: { submittedAt: "desc" },
    select: { id: true },
  });

  const base = {
    status: input.status,
    submissionNote: input.submissionNote ?? null,
    submittedById: input.submittedById,
    decidedById: input.status === "Submitted" ? null : input.decidedById,
    decidedAt: input.status === "Submitted" ? null : new Date(),
    rejectionReason: input.status === "Rejected" ? "Missing field mismatch needs clarification." : null,
    managerResponseKind: input.managerResponseKind ?? null,
    managerResponseLabel: input.managerResponseLabel ?? null,
    managerResponseNote: input.managerResponseNote ?? null,
    managerRespondedAt: input.managerResponseKind ? new Date() : null,
    managerRespondedById: input.managerResponseKind ? input.decidedById : null,
  };

  if (existing) {
    return prisma.workItemApproval.update({
      where: { id: existing.id },
      data: base,
    });
  }

  return prisma.workItemApproval.create({
    data: {
      workItemId: input.workItemId,
      ...base,
    },
  });
}

async function ensureDocument(input: {
  organizationId: number;
  clientEntityId?: number | null;
  ownerUserId: number;
  uploadedById: number;
  title: string;
  sourceType: string;
  fileName: string;
  folder: string;
  contentText: string;
}) : Promise<SeededDocument> {
  const existing = await prisma.document.findFirst({
    where: {
      organizationId: input.organizationId,
      archivedAt: null,
      title: input.title,
      sourceType: input.sourceType,
      ownerUserId: input.ownerUserId,
    },
    select: {
      id: true,
      versions: {
        select: { id: true, fileName: true, isCurrent: true, versionNumber: true },
        orderBy: [{ isCurrent: "desc" }, { versionNumber: "desc" }, { id: "desc" }],
        take: 1,
      },
    },
  });

  if (existing?.versions?.[0]) {
    const version = existing.versions[0];
    return {
      documentId: existing.id,
      documentVersionId: version.id,
      fileName: version.fileName,
      fileUrl: buildDocumentDownloadUrl(existing.id, version.id),
    };
  }

  const buffer = Buffer.from(input.contentText, "utf8");
  const registered = await registerDocumentUpload(prisma, {
    buffer,
    fileName: input.fileName,
    mimeType: "text/plain",
    folder: input.folder,
    title: input.title,
    sourceType: input.sourceType,
    organizationId: input.organizationId,
    clientEntityId: input.clientEntityId ?? null,
    ownerUserId: input.ownerUserId,
    uploadedById: input.uploadedById,
  });

  return {
    documentId: registered.documentId,
    documentVersionId: registered.documentVersionId,
    fileName: registered.fileName,
    fileUrl: registered.fileUrl,
  };
}

async function upsertEvidence(input: {
  workItemId: number;
  uploadedById: number;
  label: string;
  seededDocument: SeededDocument;
}) {
  const existing = await prisma.workItemEvidence.findFirst({
    where: {
      workItemId: input.workItemId,
      isCurrent: true,
      documentVersionId: input.seededDocument.documentVersionId,
    },
    select: { id: true },
  });

  if (existing) {
    return prisma.workItemEvidence.update({
      where: { id: existing.id },
      data: {
        label: input.label,
        fileUrl: input.seededDocument.fileUrl,
        fileName: input.seededDocument.fileName,
        documentId: input.seededDocument.documentId,
        documentVersionId: input.seededDocument.documentVersionId,
        uploadedById: input.uploadedById,
        isCurrent: true,
      },
    });
  }

  return prisma.workItemEvidence.create({
    data: {
      workItemId: input.workItemId,
      kind: "PROOF",
      label: input.label,
      fileUrl: input.seededDocument.fileUrl,
      fileName: input.seededDocument.fileName,
      documentId: input.seededDocument.documentId,
      documentVersionId: input.seededDocument.documentVersionId,
      uploadedById: input.uploadedById,
      isCurrent: true,
    },
  });
}

async function upsertVerification(input: {
  seededDocument: SeededDocument;
  workItemId: number;
  status: "MATCHED" | "MISMATCH" | "CHECK_NEEDED";
  summary: string;
  fields: Record<string, unknown>;
  mismatches?: Record<string, unknown>;
}) {
  return prisma.documentVerification.upsert({
    where: {
      documentVersionWorkItemVerification: {
        documentVersionId: input.seededDocument.documentVersionId,
        workItemId: input.workItemId,
        verificationSource: "SYSTEM",
      },
    },
    update: {
      status: input.status,
      summary: input.summary,
      fields: input.fields as Prisma.InputJsonValue,
      mismatches: input.mismatches
        ? (input.mismatches as Prisma.InputJsonValue)
        : Prisma.JsonNull,
      verifiedAt: new Date(),
    },
    create: {
      documentId: input.seededDocument.documentId,
      documentVersionId: input.seededDocument.documentVersionId,
      workItemId: input.workItemId,
      status: input.status,
      verificationSource: "SYSTEM",
      summary: input.summary,
      fields: input.fields as Prisma.InputJsonValue,
      mismatches: input.mismatches
        ? (input.mismatches as Prisma.InputJsonValue)
        : Prisma.JsonNull,
    },
  });
}

async function upsertNotification(input: {
  dedupeKey: string;
  status: NotificationStatus;
  stage: NotificationStage;
  recipient: string;
  messagePreview: string;
  workItemId?: number | null;
  userId?: number | null;
  errorMessage?: string | null;
  retryCount?: number;
}) {
  return prisma.notificationLog.upsert({
    where: { dedupeKey: input.dedupeKey },
    update: {
      status: input.status,
      stage: input.stage,
      recipient: input.recipient,
      messagePreview: input.messagePreview,
      workItemId: input.workItemId ?? null,
      userId: input.userId ?? null,
      errorMessage: input.errorMessage ?? null,
      retryCount: input.retryCount ?? 0,
      lastAttemptAt: new Date(),
      sentAt: input.status === NotificationStatus.SENT ? new Date() : null,
    },
    create: {
      channel: NotificationChannel.WHATSAPP,
      stage: input.stage,
      status: input.status,
      recipient: input.recipient,
      messagePreview: input.messagePreview,
      dedupeKey: input.dedupeKey,
      workItemId: input.workItemId ?? null,
      userId: input.userId ?? null,
      errorMessage: input.errorMessage ?? null,
      retryCount: input.retryCount ?? 0,
      lastAttemptAt: new Date(),
      sentAt: input.status === NotificationStatus.SENT ? new Date() : null,
    },
  });
}

async function upsertDecision(input: {
  organizationId: number;
  clientEntityId?: number | null;
  workItemId?: number | null;
  documentId?: number | null;
  documentVersionId?: number | null;
  requestedById: number;
  assignedToId: number;
  kind: WorkDecisionKind;
  status: WorkDecisionStatus;
  title: string;
  summary: string;
  dueAt?: Date | null;
}) {
  const existing = await prisma.workDecision.findFirst({
    where: { organizationId: input.organizationId, title: input.title },
    select: { id: true },
  });

  const data = {
    kind: input.kind,
    status: input.status,
    title: input.title,
    summary: input.summary,
    dueAt: input.dueAt ?? null,
    organizationId: input.organizationId,
    clientEntityId: input.clientEntityId ?? null,
    workItemId: input.workItemId ?? null,
    documentId: input.documentId ?? null,
    documentVersionId: input.documentVersionId ?? null,
    requestedById: input.requestedById,
    assignedToId: input.assignedToId,
  };

  if (existing) {
    return prisma.workDecision.update({ where: { id: existing.id }, data });
  }

  return prisma.workDecision.create({ data });
}

async function main() {
  const namespace = process.env.SEED_NAMESPACE?.trim() || "demo-v1";
  const orgSlug = process.env.SEED_ORG_SLUG?.trim() || "bhl-demo";
  const orgName = process.env.SEED_ORG_NAME?.trim() || "BHL Demo Organization";

  console.log(`[seed] Using org ${orgSlug}`);

  const organization = await upsertOrganization({ slug: orgSlug, name: orgName });

  const director = await upsertUser({
    organizationId: organization.id,
    email: "director@bhl.demo",
    name: "Demo Director",
    role: Role.ADMIN,
    phoneNumber: "+254701000001",
    whatsappOptIn: true,
  });
  const accountant = await upsertUser({
    organizationId: organization.id,
    email: "accountant@bhl.demo",
    name: "Demo Accountant",
    role: Role.ACCOUNTANT,
    phoneNumber: "+254701000002",
    whatsappOptIn: true,
  });
  const hr = await upsertUser({
    organizationId: organization.id,
    email: "hr@bhl.demo",
    name: "Demo HR",
    role: Role.HR,
    phoneNumber: "+254701000003",
    whatsappOptIn: false,
  });
  const ops = await upsertUser({
    organizationId: organization.id,
    email: "ops@bhl.demo",
    name: "Demo Operations",
    role: Role.OPERATIONS_MANAGER,
    phoneNumber: "+254701000004",
    whatsappOptIn: true,
  });
  const staff = await upsertUser({
    organizationId: organization.id,
    email: "staff@bhl.demo",
    name: "Demo Staff",
    role: Role.USER,
    phoneNumber: "+254701000005",
    whatsappOptIn: true,
  });

  const clientAcme = await upsertClientEntity({
    organizationId: organization.id,
    name: "Acme Construction Ltd",
    code: "ACME",
  });
  const clientLogistics = await upsertClientEntity({
    organizationId: organization.id,
    name: "Ruiru Logistics Ltd",
    code: "RLL",
  });
  const clientIct = await upsertClientEntity({
    organizationId: organization.id,
    name: "Nairobi ICT Services Ltd",
    code: "NICT",
  });

  // Training demo
  const trainingStart = daysFromNow(14, 10, 0);
  const trainingEnd = daysFromNow(14, 16, 0);
  const existingTraining = await prisma.training.findFirst({
    where: { title: "Q2 Compliance & CPD Training", createdById: hr.id },
    orderBy: { id: "desc" },
    select: { id: true },
  });
  const training = existingTraining
    ? await prisma.training.update({
        where: { id: existingTraining.id },
        data: {
          description: "Demo training seed for CPD tracking.",
          startDate: trainingStart,
          endDate: trainingEnd,
          location: "Nairobi (Demo)",
          budgetKES: 5000,
          costKES: 4500,
          status: TrainingStatus.SCHEDULED,
        },
      })
    : await prisma.training.create({
        data: {
          title: "Q2 Compliance & CPD Training",
          description: "Demo training seed for CPD tracking.",
          startDate: trainingStart,
          endDate: trainingEnd,
          location: "Nairobi (Demo)",
          budgetKES: 5000,
          costKES: 4500,
          status: TrainingStatus.SCHEDULED,
          createdById: hr.id,
        },
      });

  await prisma.attendance.upsert({
    where: { userId_trainingId: { userId: ops.id, trainingId: training.id } },
    update: { attended: true },
    create: { userId: ops.id, trainingId: training.id, attended: true },
  });

  // WorkItems (mix of due soon + overdue)
  const paye = await ensureWorkItem({
    namespace,
    key: "paye-apr",
    organizationId: organization.id,
    clientEntityId: clientAcme.id,
    userId: accountant.id,
    title: "PAYE Filing (Monthly)",
    category: "PAYROLL",
    deadline: daysFromNow(2, 9, 0),
    frequency: "MONTHLY",
    responsible: accountant.name || accountant.email,
    requiredDocumentLabel: "KRA filing receipt",
    status: "Pending",
    riskScore: "HIGH",
  });

  const vat = await ensureWorkItem({
    namespace,
    key: "vat-apr",
    organizationId: organization.id,
    clientEntityId: clientAcme.id,
    userId: accountant.id,
    title: "VAT Return (Monthly)",
    category: "TAX",
    deadline: daysFromNow(7, 9, 0),
    frequency: "MONTHLY",
    responsible: accountant.name || accountant.email,
    requiredDocumentLabel: "VAT iTax confirmation",
    status: "Pending",
    riskScore: "MEDIUM",
  });

  const nssf = await ensureWorkItem({
    namespace,
    key: "nssf-apr",
    organizationId: organization.id,
    clientEntityId: clientLogistics.id,
    userId: ops.id,
    title: "NSSF Payment (Monthly)",
    category: "STATUTORY",
    deadline: daysFromNow(1, 9, 0),
    frequency: "MONTHLY",
    responsible: ops.name || ops.email,
    requiredDocumentLabel: "NSSF payment slip",
    status: "Submitted",
    riskScore: "HIGH",
  });

  const businessPermit = await ensureWorkItem({
    namespace,
    key: "permit-overdue",
    organizationId: organization.id,
    clientEntityId: clientIct.id,
    userId: staff.id,
    title: "Business Permit Renewal",
    category: "RENEWALS",
    deadline: daysFromNow(-10, 9, 0),
    frequency: "ANNUALLY",
    responsible: staff.name || staff.email,
    requiredDocumentLabel: "County permit receipt",
    status: "Pending",
    riskScore: "HIGH",
  });

  await replaceChecklist(paye.id, [
    "Pull payroll summary for the month",
    "File PAYE on iTax",
    "Upload KRA filing receipt",
  ]);
  await replaceChecklist(vat.id, [
    "Export sales + purchases VAT ledger",
    "Submit VAT return on iTax",
    "Upload VAT confirmation slip",
  ]);
  await replaceChecklist(nssf.id, [
    "Confirm headcount and total pensionable pay",
    "Generate NSSF PRN / payment slip",
    "Upload NSSF payment slip",
  ]);
  await replaceChecklist(businessPermit.id, [
    "Confirm county rate / fee",
    "Pay via eCitizen / county portal",
    "Upload permit receipt",
  ]);

  // Approvals + manager responses
  const nssfApproval = await upsertApproval({
    workItemId: nssf.id,
    submittedById: ops.id,
    decidedById: director.id,
    status: "Submitted",
    submissionNote: "Submitted proof for NSSF payment. Please confirm PRN + amount.",
    managerResponseKind: "SEEN",
    managerResponseLabel: "Seen",
    managerResponseNote: "Reviewing now.",
  });

  // Documents + evidence
  const payeDoc = await ensureDocument({
    organizationId: organization.id,
    clientEntityId: clientAcme.id,
    ownerUserId: accountant.id,
    uploadedById: accountant.id,
    title: "KRA PAYE receipt (demo)",
    sourceType: "KRA_RECEIPT",
    folder: "demo/receipts",
    fileName: "kra-paye-receipt-demo.txt",
    contentText: buildReceiptText({
      authority: "KRA",
      receiptNo: "KRA-PRN-834921",
      date: new Date().toISOString().slice(0, 10),
      amountKes: 182_500,
      payer: clientAcme.name,
      pin: "P051234567X",
      prn: "PRN-834921",
    }),
  });

  const nssfDoc = await ensureDocument({
    organizationId: organization.id,
    clientEntityId: clientLogistics.id,
    ownerUserId: ops.id,
    uploadedById: ops.id,
    title: "NSSF payment slip (demo)",
    sourceType: "NSSF_RECEIPT",
    folder: "demo/receipts",
    fileName: "nssf-slip-demo.txt",
    contentText: buildReceiptText({
      authority: "NSSF",
      receiptNo: "NSSF-RCPT-22104",
      date: new Date().toISOString().slice(0, 10),
      amountKes: 36_000,
      payer: clientLogistics.name,
      prn: "NSSF-PRN-22104",
    }),
  });

  await upsertEvidence({
    workItemId: paye.id,
    uploadedById: accountant.id,
    label: "KRA receipt",
    seededDocument: payeDoc,
  });
  await upsertEvidence({
    workItemId: nssf.id,
    uploadedById: ops.id,
    label: "NSSF slip",
    seededDocument: nssfDoc,
  });

  await upsertVerification({
    seededDocument: payeDoc,
    workItemId: paye.id,
    status: "MATCHED",
    summary: "Receipt number and filing date appear consistent with the work item.",
    fields: {
      receiptNumber: "KRA-PRN-834921",
      amountKES: 182500,
      filingDate: new Date().toISOString().slice(0, 10),
      pin: "P051234567X",
    },
  });

  await upsertVerification({
    seededDocument: nssfDoc,
    workItemId: nssf.id,
    status: "CHECK_NEEDED",
    summary: "PRN found but amount requires manager confirmation against the portal.",
    fields: {
      receiptNumber: "NSSF-RCPT-22104",
      prn: "NSSF-PRN-22104",
      amountKES: 36000,
      paymentDate: new Date().toISOString().slice(0, 10),
    },
    mismatches: {
      amount: {
        expected: 40000,
        found: 36000,
        note: "Headcount changed mid-month; confirm correct payable amount.",
      },
    },
  });

  // Decision Ops: manager inbox items
  await upsertDecision({
    organizationId: organization.id,
    clientEntityId: clientLogistics.id,
    workItemId: nssf.id,
    documentId: nssfDoc.documentId,
    documentVersionId: nssfDoc.documentVersionId,
    requestedById: ops.id,
    assignedToId: director.id,
    kind: WorkDecisionKind.PAYMENT_APPROVAL,
    status: WorkDecisionStatus.OPEN,
    title: `[${namespace}] Approve NSSF payment amount`,
    summary: "Confirm the NSSF amount matches the portal before marking the work item approved.",
    dueAt: daysFromNow(1, 13, 0),
  });

  await upsertDecision({
    organizationId: organization.id,
    clientEntityId: clientAcme.id,
    workItemId: paye.id,
    documentId: payeDoc.documentId,
    documentVersionId: payeDoc.documentVersionId,
    requestedById: accountant.id,
    assignedToId: director.id,
    kind: WorkDecisionKind.DOCUMENT_DECISION,
    status: WorkDecisionStatus.OPEN,
    title: `[${namespace}] Confirm PAYE receipt`,
    summary: "Quick check that the KRA PAYE receipt number is correctly captured.",
    dueAt: daysFromNow(1, 12, 0),
  });

  // WhatsApp delivery logs (for the delivery dashboard)
  await upsertNotification({
    dedupeKey: `${namespace}:paye:pre_due`,
    status: NotificationStatus.SENT,
    stage: NotificationStage.ASSIGNEE_PRE_DUE,
    recipient: accountant.phoneNumber || "+254701000002",
    messagePreview: `PAYE due ${paye.deadline.toISOString().slice(0, 10)} for ${clientAcme.name}.`,
    workItemId: paye.id,
    userId: accountant.id,
  });

  await upsertNotification({
    dedupeKey: `${namespace}:nssf:approval_nudge`,
    status: NotificationStatus.FAILED,
    stage: NotificationStage.MANAGER_APPROVAL_NUDGE,
    recipient: director.phoneNumber || "+254701000001",
    messagePreview: `Waiting on approval: NSSF payment for ${clientLogistics.name}.`,
    workItemId: nssf.id,
    userId: director.id,
    errorMessage: "Demo failure: provider timeout.",
    retryCount: 2,
  });

  await upsertNotification({
    dedupeKey: `${namespace}:director:morning_digest`,
    status: NotificationStatus.SENT,
    stage: NotificationStage.MANAGER_MORNING_DIGEST,
    recipient: director.phoneNumber || "+254701000001",
    messagePreview: `Manager digest: 2 open decisions, 1 submitted item awaiting approval.`,
    userId: director.id,
  });

  // Keep a couple audit entries so the audit trails page feels real (idempotent).
  const auditSeeds = [
    {
      workItemId: nssf.id,
      eventType: "SUBMITTED",
      detail: "Submitted with proof for manager review.",
      actorUserId: ops.id,
    },
    {
      workItemId: nssf.id,
      eventType: "MANAGER_SEEN",
      detail: "Manager acknowledged receipt of submission.",
      actorUserId: director.id,
    },
  ];

  for (const seed of auditSeeds) {
    const exists = await prisma.workItemAuditEvent.findFirst({
      where: {
        workItemId: seed.workItemId,
        eventType: seed.eventType,
        detail: seed.detail,
      },
      select: { id: true },
    });

    if (!exists) {
      await prisma.workItemAuditEvent.create({ data: seed });
    }
  }

  console.log("[seed] Demo data ready.");
  console.log("[seed] Logins (password: password123): director@bhl.demo, accountant@bhl.demo, ops@bhl.demo, hr@bhl.demo, staff@bhl.demo");
  console.log(`[seed] Document download example: ${payeDoc.fileUrl}`);
  console.log(`[seed] Approval record id: ${nssfApproval.id}`);
}

main()
  .catch((error) => {
    console.error("[seed] Failed:", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end().catch(() => undefined);
  });
